# Designing a RandomForest Classifier

In [31]:
import pandas as pd
import numpy as np
import seaborn as sn
import PIL
import random
from sklearn import tree
random.seed(10)
from PIL import Image
from numpy import asarray
from scipy import stats
from statistics import mode
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
#converting from train images to points
points=np.empty([2400,785])
for i in range(1,2401):
    path =r'C:\Users\hp\Desktop\Train/'+ str(i)+'.jpg'
    an_image = PIL.Image.open(path)
    image_sequence = an_image.getdata()
    image_array = np.array(image_sequence)
    image_array = np.append (image_array,[1])
    x=image_array.reshape(1,785) 
    points[i-1]=x    

In [3]:
#converting from test images to points
test_points=np.empty([200,785])
for i in range(1,201):
    path =r'C:\Users\hp\Desktop\Test/'+str(i)+'.jpg'
    an_image = PIL.Image.open(path)
    image_sequence = an_image.getdata()
    image_array = np.array(image_sequence)
    image_array = np.append (image_array,[1])
    x=image_array.reshape(1,785) 
    test_points[i-1]=x    

In [4]:
#reading train labels
f=open(r'C:\Users\hp\Desktop\Train\Training Labels.txt', mode='r')
l=f.read()
labels=[]
for i in range(0,4800):
    if (i%2==0):
        labels.append(l[i])

In [5]:
#reading test labels
f=open(r'C:\Users\hp\Desktop\Test\Test Labels.txt', mode='r')
l=f.read()
test_labels=[]
for i in range(0,400):
    if (i%2==0):
        test_labels.append(l[i])  
        
for i in range(0,200):
    if (test_labels[i]=='0'):
        test_labels[i]=0
    elif (test_labels[i]=='1'):
        test_labels[i]=1
    elif (test_labels[i]=='2'):
        test_labels[i]=2
    elif (test_labels[i]=='3'):
        test_labels[i]=3
    elif (test_labels[i]=='4'):
        test_labels[i]=4
    elif (test_labels[i]=='5'):
        test_labels[i]=5
    elif (test_labels[i]=='6'):
        test_labels[i]=6
    elif (test_labels[i]=='7'):
        test_labels[i]=7
    elif (test_labels[i]=='8'):
        test_labels[i]=8
    elif (test_labels[i]=='9'):
        test_labels[i]=9

In [6]:
def CreateSamples(points,labels,s):
    label=np.zeros(s)
    sample=np.zeros((s,785))
    for i in range(s):
        r=random.randint(0,2399)
        label[i]=labels[r]
        sample[i]=points[r]
    label=label.reshape(s,1)
    sl=np.append(sample, label, axis = 1)
    return sl

In [7]:
#n=numer of trees/s=num of samples/m=max_depth
def Predictions(points,test_points,labels,n,s,m):
    flag=True
    for i in range(n):
        sl=CreateSamples(points,labels,s)
        slabels=sl[:,785]
        samples=np.delete(sl, 785, 1)
        X, y = samples,slabels
        clf = tree.DecisionTreeClassifier(max_depth=m, random_state=10)
        clf = clf.fit(X, y)
        pred=clf.predict(test_points)
        pred=pred.reshape(200,1)
        if(flag==True):
            flag=False
            predictions=pred
        else:
            predictions=np.append(predictions,pred,axis=1)
    return predictions

In [20]:
def RandomForest(predictions):
    RFpred=np.zeros(200)
    for i in range(200):
        RFpred[i]=mode(predictions[i])
    return RFpred

In [16]:
def Accuracy(test_labels,RFpred):
    acc=0
    for i in range (200):
        if(test_labels[i]==RFpred[i]):
            acc+=1
    acc=(acc/200)*100
    return acc

### 1) NumOfTrees = 10, NumOfSamples = 50 and MaxDepth = 10

In [22]:
#                                             Accuracy
predictions1=Predictions(points,test_points,labels,10,50,10)
RFpred1=RandomForest(predictions1)
print(Accuracy(test_labels,RFpred1))

55.00000000000001


In [23]:
#                                          Confusion_Matrix
confusion_matrix(test_labels,RandomForest(predictions1))

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 19,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 2,  0, 17,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  2, 14,  0,  1,  0,  3,  0,  0],
       [ 3,  1,  3,  2,  4,  0,  0,  2,  1,  4],
       [ 5,  0,  1,  1,  0,  4,  0,  1,  2,  6],
       [ 8,  0,  1,  1,  1,  2,  7,  0,  0,  0],
       [ 2,  1,  0,  0,  0,  0,  0,  9,  0,  8],
       [ 0,  4,  1,  2,  0,  2,  0,  0, 11,  0],
       [ 1,  0,  1,  2,  1,  0,  2,  7,  0,  6]], dtype=int64)

### 2)NumOfTrees = 100, NumOfSamples = 50 and MaxDepth = 10

In [24]:
#                                             Accuracy
predictions2=Predictions(points,test_points,labels,100,50,10)
RFpred2=RandomForest(predictions2)
print(Accuracy(test_labels,RFpred2))

72.0


In [25]:
#                                          Confusion_Matrix
confusion_matrix(test_labels,RandomForest(predictions2))

array([[18,  0,  0,  0,  0,  0,  1,  0,  1,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  4, 11,  1,  1,  0,  0,  0,  2,  0],
       [ 0,  2,  0, 14,  0,  3,  0,  0,  1,  0],
       [ 1,  1,  1,  0, 11,  0,  1,  0,  0,  5],
       [ 1,  1,  0,  1,  0, 15,  0,  0,  0,  2],
       [ 3,  0,  0,  0,  2,  0, 15,  0,  0,  0],
       [ 0,  1,  0,  0,  2,  0,  0, 14,  0,  3],
       [ 1,  0,  0,  0,  0,  0,  0,  0, 17,  2],
       [ 3,  0,  1,  0,  3,  0,  0,  4,  0,  9]], dtype=int64)

### 3)NumOfTrees = 100, NumOfSamples = 500 and MaxDepth = 10

In [26]:
#                                             Accuracy
predictions3=Predictions(points,test_points,labels,100,500,10)
RFpred3=RandomForest(predictions3)
print(Accuracy(test_labels,RFpred3))

85.0


In [27]:
#                                          Confusion_Matrix
confusion_matrix(test_labels,RandomForest(predictions3))

array([[17,  0,  0,  0,  0,  2,  1,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 17,  1,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 16,  0,  2,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 19,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  2,  0, 16,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0, 19,  0,  0,  0],
       [ 0,  1,  0,  0,  1,  0,  0, 16,  0,  2],
       [ 1,  0,  0,  1,  0,  0,  0,  0, 17,  1],
       [ 1,  0,  0,  0,  2,  0,  0,  4,  0, 13]], dtype=int64)

### 4)NumOfTrees = 100 NumOfSamples = 1000 and MaxDepth = 100

In [28]:
#                                             Accuracy
predictions4=Predictions(points,test_points,labels,100,1000,100)
RFpred4=RandomForest(predictions4)
print(Accuracy(test_labels,RFpred4))

88.5


In [29]:
#                                          Confusion_Matrix
confusion_matrix(test_labels,RandomForest(predictions4))

array([[18,  0,  0,  0,  1,  0,  1,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 17,  1,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 17,  0,  1,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 17,  0,  1,  0,  0,  2],
       [ 0,  0,  0,  1,  0, 19,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0, 19,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 19,  0,  1],
       [ 1,  0,  0,  1,  0,  0,  0,  0, 18,  0],
       [ 1,  0,  0,  0,  3,  0,  0,  2,  1, 13]], dtype=int64)